services:
  - type: web
    name: voice-agent-backend
    env: python
    runtime: python3.10
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    rootDir: agent/backend
    autoDeploy: true

  - type: static
    name: voice-agent-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    rootDir: agent/frontend
    branch: main
    autoDeploy: true
