services:
  - type: web
    name: voice-agent-backend
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    rootDir: backend
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-key
      - key: AGORA_APP_ID
        value: your-agora-app-id
      - key: AGORA_APP_CERTIFICATE
        value: your-agora-app-certificate
      - key: GOOGLE_SHEET_ID
        value: your-google-sheet-id
      - key: GOOGLE_CREDENTIALS_JSON
        value: '{"type": "...", "project_id": "..."}'
      - key: GITHUB_KB_REPO
        value: rajnish2424/Voice-assistant--AP
