services:
  - type: web
    name: voice-agent-backend
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    rootDir: backend
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_APP_CERTIFICATE
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GITHUB_KB_REPO
        value: rajnish2424/Voice-assistant--AP
